### ISSUE TITLE
ICP理解测试

### ISSUE THREAD

**Issue by nullscc** [nullscc/icp_test#10]
ICP理解测试issue @maohuaming

**Comment by maohuaming** [comment]
@nullscc 开始ICP理解测试。第一个问题：小白是一个什么样的组织？

**Comment by nullscc** [comment]
@maohuaming 小白是一个采用众和方式推动的青色组织。

**Comment by maohuaming** [comment]
@nullscc 回答正确。下一个问题：众和的核心思想是什么？

**Comment by nullscc** [comment]
@maohuaming 众和的核心思想是：以尊重和信任为基础，自主参与为形式，公正奖励为机制，以实现高效、可持续、可预期的商业目标的众人和合形式。

**Comment by maohuaming** [comment]
@nullscc 回答正确。下一个问题：小白社区的价值观是什么？

**Comment by nullscc** [comment]
@maohuaming  小白社区的价值观是：
* 尊重、信任；
* 愿以悲悯之心为公众的健康做贡献
* 严格的执行标准；
* 协作和为协作提供便利；
* 当你没有时间时，请告诉大家；
* 保障信息的安全；

**Comment by maohuaming** [comment]
@nullscc 回答正确。下一个问题：合格贡献者的条件是什么？

**Comment by nullscc** [comment]
@maohuaming 合格贡献者的条件是：
1. 个人，不得是组织、团队
2. 认同小白众和的理念和价值观
3. 通过ICP流程认证

**Comment by maohuaming** [comment]
@nullscc 下一题：如何申请开发一个issue？

**Comment by nullscc** [comment]
@maohuaming 在issue的comment中写一个独立的comment，内容格式：
`申请开发 deadline:yyyy-mm-dd size xx @xxx`

**Comment by maohuaming** [comment]
@nullscc 回答正确。下一个问题：PR中如何引用一个issue？

**Comment by nullscc** [comment]
@maohuaming 使用如下格式：`for #<issue 编号>`

**Comment by maohuaming** [comment]
@nullscc 回答不完全正确，请参见：https://github.com/sibbay-ai/public 5.6节。
![default](https://user-images.githubusercontent.com/28720671/43762830-9ae315f0-9a5b-11e8-8ae7-31d6af737f9d.png)

**Comment by nullscc** [comment]
@maohuaming ok，更正如下：在PR中书写如下格式`fix|for:issue-url [文字]`，每一行写一个issue

**Comment by maohuaming** [comment]
@nullscc 记违规一次。下一个问题：PR中包含的commit如何命名？

**Comment by nullscc** [comment]
@maohuaming 使用以下格式：`for <#issue编号> 描述`

**Comment by maohuaming** [comment]
@nullscc 回答不正确，请参见：https://github.com/sibbay-ai/public/blob/master/pull%20request%20%E8%A7%84%E8%8C%83.md

**Comment by nullscc** [comment]
@maohuaming 哪里不正确呢？

**Comment by maohuaming** [comment]
@nullscc 
![default](https://user-images.githubusercontent.com/28720671/43763836-64072b18-9a5e-11e8-9dd4-8a8d5ec22fcf.png)
你答案的依据是哪一个？

**Comment by nullscc** [comment]
@maohuaming commit的最重要的是 `#<issue 编号>`,难道我理解的有误吗？ 我的错误在哪里呢？

**Comment by maohuaming** [comment]
@nullscc 主要是为了统一格式，社区的负责人不希望格式搞的五花八门。要不然就不会制定这条规则了。

**Comment by nullscc** [comment]
@maohuaming 我理解这点，但是对于小白项目来说，一个commit主要需要达到以下两点：
1. 引用issue
2. 为此commit做必要的说明

我的答案只是没有原样复制而已，完全达到社区的要求，社区不至于如此死板吧？

**Comment by maohuaming** [comment]
@nullscc 这个问题，你可以向社区管理者提出异议。但是目前定的规则，我要严格执行的。

**Comment by nullscc** [comment]
@maohuaming ok,理解，可以下一步了吗？还是 ？

**Comment by maohuaming** [comment]
@nullscc 记违规一次。下一个问题：pull 对应的分支应该如何命名？

**Comment by nullscc** [comment]
@maohuaming pull 对应的分支应该按照 类型/开发者-目的 命名。
可取的类型包括：bugfix(修 BUG) feature(功能特性开发) doc(文档工作)
例如，ben7th 修正图表显示不正确的 bug，可以表示为：
bugfix/ben7th-chart-error

**Comment by maohuaming** [comment]
@nullscc 回答正确。下一个问题：有效pr条件是什么？提示：请仔细阅读ICP流程图下方的文字说明。

**Comment by nullscc** [comment]
@maohuaming 有效pr的条件是:
1. committer指定assigness; 
2. assigness在有效时间范围内merge ; 
3. committer打上了icp label; 
4. 如果有size，则必须由committer打上的;(可以没有)

**Comment by maohuaming** [comment]
@nullscc 回答正确。下一个问题：有效issue条件是什么？

**Comment by nullscc** [comment]
@maohuaming 有效issue条件:
1. committer指定了assigness; 
2. committer打上了size的label; 
3. 有效pr对issue进行了有效引用 
4. pr的merge时间早于有效deadline时间 
5. close
6. 没有"失败" label

**Comment by maohuaming** [comment]
@nullscc 回答正确。下一个问题：有效deadline条件是什么？

**Comment by nullscc** [comment]
@maohuaming 有效deadline条件:
1. committer在独立comment中撰写的最后一次deadline， 文 字格式:`deadline:yyyy-mm-dd [@xx 文字](独立comment) `
2. 当committer没有指定deadline时，assigness在独立comment 中撰写的第一次deadline，且撰写时间早于issue被pr引用的时间， 文字格式: `deadline:yyyy-mm-dd [@xx 文字](独立comment)`

**Comment by maohuaming** [comment]
@nullscc 回答正确。下一个问题：pr对issue如何有效引用？

**Comment by nullscc** [comment]
@maohuaming 在pr的正文或comment中撰写如下文字：`fix|for:issue-url [文字]`， 每一行写一个issue

**Comment by maohuaming** [comment]
@nullscc 回答正确。下一个问题：pr对issue有效的引用包含两种情况，请说明。

**Comment by nullscc** [comment]
@maohuaming 
1. pr的creater在pr merge之前进行了引用，文字格式: for[fix]:issue url (一个issue独立一行) 
2. pr的assigness在pr的comment进行了引用: for[fix]:issue url (一个issue独立一行)

**Comment by maohuaming** [comment]
@nullscc 回答正确。认证结束。

**Comment by nullscc** [comment]
@maohuaming 多谢！
