### ISSUE TITLE
ICP协作

### ISSUE THREAD

**Issue by nullscc** [nullscc/icp_test#4]
@maohuaming

**Comment by maohuaming** [comment]
@nullscc 现在开始ICP认证。开始时间：2018-08-07 10:43

**Comment by maohuaming** [comment]
@nullscc 请新建一个需求开发issue。

**Comment by nullscc** [comment]
@maohuaming ok

**Comment by nullscc** [comment]
@maohuaming 需求开发issue建立完成

**Comment by maohuaming** [comment]
@nullscc 重新建一个需求issue，我们把流程再重新走一遍。

**Comment by nullscc** [comment]
@maohuaming 建立完成 #6

**Comment by nullscc** [comment]
@maohuaming 是否需要等待分配size label才能进行开发？

**Comment by maohuaming** [comment]
@nullscc 继续认证。请新建一个bug修复issue。

**Comment by nullscc** [comment]
@maohuaming bug修复issue建立完成， #8

**Comment by nullscc** [comment]
@maohuaming bug issue合并PR完成，合并完成后相关issue由committer关闭还是由contributor关闭？

**Comment by maohuaming** [comment]
@nullscc 都可以关闭。

**Comment by maohuaming** [comment]
@nullscc 请新建一个issue，名称为：ICP理解测试。

**Comment by nullscc** [comment]
@maohuaming ICP理解测试建立完成
