### ISSUE TITLE
需求issue

### ISSUE THREAD

**Issue by nullscc** [nullscc/icp_test#5]
icp认证之需求开发issue

**Comment by nullscc** [comment]
申请开发，deadline:2018-8-7 size:0.5 @maohuaming

**Comment by maohuaming** [comment]
@nullscc 有个地方违规了，请注意一下。
1.注意一下操作权限，你的角色是contributor，我是committer。流程图里，每一个步骤都标有绿色和黄色的人形logo，表示哪个角色可以操作这一步。
2.assignee应当由committer来指定。
3.ICP标签也是有committer来打。

**Comment by nullscc** [comment]
@maohuaming 好的，了解了
