### ISSUE TITLE
需求issue

### ISSUE THREAD

**Issue by nullscc** [nullscc/icp_test#6]
icp认证之需求issue

**Comment by maohuaming** [comment]
@nullscc 已经打上ICP标签，请申请开发。

**Comment by nullscc** [comment]
申请开发 deadline:2018-8-7 size:0.5 @maohuaming

**Comment by maohuaming** [comment]
@nullscc 申请开发的格式有错误，“申请开发”后面不能有逗号。

**Comment by nullscc** [comment]
@maohuaming 已修正

**Comment by maohuaming** [comment]
@nullscc 记违规一次。

**Comment by nullscc** [comment]
@maohuaming 了解

**Comment by maohuaming** [comment]
@nullscc 已指定assignee，打上size标签。请上传文件，并提交PR。

**Comment by nullscc** [comment]
@maohuaming 已提交PR
