### ISSUE TITLE
bug修复issue

### ISSUE THREAD

**Issue by nullscc** [nullscc/icp_test#8]
ICP认证之bug修复issue

**Comment by maohuaming** [comment]
@nullscc 已经打上ICP标签，请申请开发。

**Comment by nullscc** [comment]
申请开发 deadline:2018-8-7 size:0.5 @maohuaming

**Comment by maohuaming** [comment]
@nullscc 已指定assignee，打上size标签。请上传文件，创建PR。

**Comment by nullscc** [comment]
@maohuaming 已创建PR

**Comment by nullscc** [comment]
@maohuaming PR合并完成
